(define (square x) (* x x))
(define (sum_of_squares x y) (+ (square x)
                                (square y)))
(define (max_sum_of_squares x y z) (sum_of_squares (if (and (> x y) (> x z)) x (if (> y z) y z))
                                                  (cond ((and (> x y) (> x z)) (if (> y z) y z))
                                                        ((and (> y x) (> y z)) (if (> x z) x z))
                                                        ((and (> z x) (> z y)) (if (> x y) x y))
                                                        )))
(max_sum_of_squares 2 3 1)
