(define (squarer a b)
  (define (process-new-value)
    (if (has-value? b)
      (if (< (get-value b) 0)
        (error "square less than 0 -- SQUARER" (get-value b))
        (set-value! a (sqrt b)))
      (set-value! b (* (get-value a) (get-value a)))))
  (define (process-forget-value)
    (set-value! a '())
    (set-value! b '()))
  (define (me request)
    (cond ((eq? request 'I-have-a-value)
             (process-new-value))
           ((eq? request 'I-lost-my-value)
             (process-forget-value))
           (else (error "Unknown request -- MULTIPLIER" request))))
  (connect a me)
  (connect b me)
  'me)
