(define (make-account balance secret)
  (define bad-password 0)
  (define call-the-cops
    (lambda () (error "OHMIGOD")))
  (define (withdraw amount)
    (if (>= balance amount)
      (begin (set! balance (- balance amount))
             balance)
      "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch m password)
    (if (eq? password secret)
      (cond ((eq? m 'withdraw) withdraw)
            ((eq? m 'deposit) deposit)
            (else (error "Unknown request -- MAKE-ACCOUNT"
                         m)))
      (begin (set! bad-password (+ 1 bad-password))
             (if (> bad-password 7) (call-the-cops))
             (lambda (x) 'bad-password))))
  dispatch)

(define acct (make-account 100 'password))
((acct 'deposit 'password) 25)
((acct 'deposit 'not-password) 25)
((acct 'deposit 'not-password) 25)
((acct 'deposit 'not-password) 25)
((acct 'deposit 'not-password) 25)
((acct 'deposit 'not-password) 25)
((acct 'deposit 'not-password) 25)
((acct 'deposit 'not-password) 25)
((acct 'deposit 'not-password) 25)
