(define (rand op)
  (cond ((eq? op 'generate)
          (let ((x random-init))
            (lambda ()
              (set! x (rand-update x))
              x)))
        ((eq? op 'reset)
         (lambda (seed)
           (let ((x seed))
             (lambda ()
               (set! x (rand-update x))
               x))))))
