; 'an-integer-starting-from steadily increases it's value
; as selections are made. Therefore, all of the possible triples
; would not be generated by the program because the combinations
; of the first elements would never be made

(define (all-pythagorean-triples)
  (let ((i (an-integer-starting-from 0))
        (j (an-integer-starting-from 0))
        (k (an-integer-starting-from 0)))
    (require (= (+ (* i i) (* j j)) (* k k)))
    (list i j k)))
