(define (eval-and exp env)
  (define (process-and . terms)
    (if ((eq? '() terms) 'true)
      (if ((eq? 'false (eval (car terms) env)) 'false)
        (process-and (cdr terms)))))
  (if ((eq? '() (cdr exp)) 'false)
    (process-and (cdr exp))))

(define (eval-or exp env)
  (define (process-or . terms)
    (if ((eq? '() terms) 'false)
      (if ((eq? 'true (eval (car terms) env)) 'true)
        (process-or (cdr terms)))))
  (if ((eq? '() (cdr exp)) 'false)
    (process-or (cdr exp))))
